Fix ptrace.h error. Changed from linux/ptrace.h to asm/ptrace.h
Part of the error:
/usr/include/linux/ptrace.h:58:8: error: redefinition of 'struct
ptrace_peeksiginfo_args'

Inspired of http://www.gossamer-threads.com/lists/linux/kernel/1771122

Change-Id: Ied5ce28a8f2572e092f737d811ddf80a9a0f5896
Signed-off-by: Victor Hakoun <victor.hakoun@eurogiciel.fr>